### ISSUE TITLE
Suggestion for "Edit Page" button

### ISSUE THREAD

**Issue by Jonny621** [newtonproject/newtonproject-org-website-2.0#6]
An optimization suggestion for [Learn menu page](https://www.newtonproject.org/en/roadmap/).
When click "Edit page" button, current browser Tab will redirect to github page.
Can it open in new browser Tab?

**Comment by liukeke-start** [comment]
Thank you for the suggestion, we have fixed it. - https://github.com/newtonproject/newtonproject-org-website-2.0/commit/354129e94b2f41fe0511732e9e629528e66ad3f8

**Comment by Jonny621** [comment]
cool
